version: '3.5'

services:
    icos-shell-backend:
        image: michalkeit/icos-shell-backend
        build: ./
        container_name: icos-shell-backend
        restart: always
        environment:
            KEYCLOAK_URL: "keycloak:443"
        ports:
            - "8080:8080"
        volumes:
            - ./config.yml:/app/config.yml
